
services:
  web:
    container_name: web_server
    image: nginx:latest
    ports:
      - '8081:80'
    networks:
      - internal
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - internal
    volumes:
      - ./src:/var/www/html

networks:
  internal:
    driver: bridge
